# Generated by Django 5.2.7 on 2025-12-18 18:46

import estoque.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', estoque.models.UserManager()),
            ],
        ),
    ]
