# Generated by Django 5.2.7 on 2025-11-08 02:12

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Solicitante',
                'verbose_name_plural': 'Solicitantes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoFracionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img/produto/fracionado')),
                ('nome', models.CharField(max_length=100)),
                ('unidade_de_medida', models.CharField(choices=[('kg', 'Quilograma'), ('g', 'Grama'), ('l', 'Litro'), ('ml', 'Mililitro'), ('m', 'Metro'), ('cm', 'Centímetro')], max_length=10)),
                ('quantidade_minima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos_fracionados', to='estoque.subcategoria')),
            ],
            options={
                'verbose_name': 'Produto Fracionado',
                'verbose_name_plural': 'Produtos Fracionados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img/produto/fracionado')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fornecedor', models.CharField(blank=True, max_length=100, null=True)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(editable=False, max_length=30, unique=True)),
                ('nome', models.CharField(editable=False, max_length=100)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='estoque.produtofracionado')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoUnitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img/produtos/unitarios/')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade_minima', models.PositiveIntegerField()),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_unitarios', to='estoque.subcategoria')),
            ],
            options={
                'verbose_name': 'Produto Unitário',
                'verbose_name_plural': 'Produtos Unitários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo', models.CharField(editable=False, max_length=30, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img/itens')),
                ('nome', models.CharField(max_length=100)),
                ('eh_do_cnatmaker', models.BooleanField()),
                ('disponibilidade', models.BooleanField(default=True)),
                ('eh_quebrado', models.BooleanField(default=False)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('eh_emprestado', models.BooleanField(default=False)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='estoque.produtounitario')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Usado apenas se a saída for de lote (produto fracionado).', max_digits=10)),
                ('data_saida', models.DateTimeField(default=django.utils.timezone.now)),
                ('responsavel', models.CharField(max_length=100)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saidas', to='estoque.item')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saidas', to='estoque.lote')),
            ],
            options={
                'verbose_name': 'Saída',
                'verbose_name_plural': 'Saídas',
                'ordering': ['-data_saida'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome', models.CharField(blank=True, max_length=200)),
                ('tipo_movimentacao', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('emprestimo', 'Empréstimo'), ('devolucao', 'Devolução')], max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_movimentacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.item')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.lote')),
                ('saida', models.ForeignKey(blank=True, help_text='Saída que originou esta movimentação, se aplicável.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='estoque.saida')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField()),
                ('previsao_entrega', models.DateTimeField()),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('responsavel', models.CharField(max_length=100)),
                ('itens', models.ManyToManyField(related_name='emprestimos', to='estoque.item')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='estoque.solicitante')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['-data_emprestimo'],
            },
        ),
    ]
