# Generated by Django 5.2.7 on 2025-11-08 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_solicitante_produtofracionado_lote_produtounitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='emprestimo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.emprestimo'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='saida',
            field=models.ForeignKey(blank=True, help_text='Saída que originou esta movimentação, se aplicável.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.saida'),
        ),
    ]
