# Generated by Django 5.2.7 on 2025-11-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_movimentacaoestoque_emprestimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtounitario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img/produto/unitario/'),
        ),
    ]
