# Generated by Django 5.2.7 on 2025-11-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_devolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitante',
            name='matricula',
            field=models.CharField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
