# Generated by Django 5.2.7 on 2025-11-09 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_solicitante_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='devolucao',
            field=models.ForeignKey(blank=True, help_text='Devolução que originou esta movimentação, se aplicável.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.devolucao'),
        ),
    ]
